[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules", "contracts/lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# via_ir = true
fs_permissions = [{ access = "read-write", path = "config/" }]
