[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "dependencies"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = "0.8.28"
evm_version = "paris"

fs_permissions = [{ access = "read-write", path = "config/" }]
gas_reports = ["ZkTLSGateway", "ZkTLSAccount", "ZkTLSManager"]

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts-upgradeable" = "5.1.0"
"@openzeppelin-contracts" = "5.1.0"
sp1-contracts = { version = "3.0.0", url = "https://github.com/succinctlabs/sp1-contracts/archive/refs/tags/v3.0.0.zip" }
risc0-ethereum = { version = "1.1.4", url = "https://github.com/risc0/risc0-ethereum/archive/refs/tags/v1.1.4.zip" }

[doc]
out = "docs"
title = "ZKTLS Contracts Docs"
book = "docs/book.toml"
ignore = [
  "contracts/mock",
  "contracts/Counter.sol",
  "contracts/Create2Deployer.sol",
  "contracts/SimpleFaucet.sol",
  "contracts/PaymentToken.sol",
]
