[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = "0.8.28"

fs_permissions = [{ access = "read-write", path = "config/" }]
gas_reports = ["ZkTLSGateway", "ZkTLSAccount", "ZkTLSManager"]

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts-upgradeable" = "5.1.0"
"@openzeppelin-contracts" = "5.1.0"
